### ISSUE TITLE
Won't import files for sins of a solar empire

### ISSUE THREAD

**Issue by Ocelotank** [ross-g/io_pdx_mesh#13]
I have a mod with pdx mesh files that I am trying to open in blender. When I try to open them with the add on, I get this error: 

Mesh import failed!
'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\carte\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_pdx_mesh\pdx_blender\blender_ui.py", line 387, in execute
    bonespace=self.chk_bonespace
  File "C:\Users\carte\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 1087, in import_meshfile
    for i, node in enumerate(shapes):
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

Is there a fix, or am I out of luck?

**Comment by ross-g** [comment]
Afraid you are out of luck. This project only supports the series of games developed by Paradox which use the [Clausewitz engine](https://en.m.wikipedia.org/wiki/Paradox_Development_Studio#Game_engines).

In other words, Sins of A Solar Empire is not supported. It's a different engine made by a different developer. Sorry!
