### ISSUE TITLE
Exporter not detecting materials/animations

### ISSUE THREAD

**Issue by Anjureux** [ross-g/io_pdx_mesh#15]
I'm trying to export a custom mesh and animation from Maya 2020 into the Stellaris PDX format. The exporter isn't detecting my animation or materials so it obviously fails to export. Help would be much appreciated!

**Comment by ross-g** [comment]
Did you get this sorted out? I've missed your post last week but it seems like just a workflow issue.
I am still planning to write a better wiki here for the tool.

**Comment by Anjureux** [comment]
Sorry, I was actually gonna move this to the Paradox forums but it wouldn't let me post it so I'm glad you found it here.

I haven't really found a fix but I think you're right in that it's a workflow issue. In Maya, everything seems to be about right since I was able to make custom meshes and animate this: https://www.youtube.com/watch?v=GpKp91uJUgQ. Now, I'm pretty sure I just didn't construct my materials right because K-vald's wiki tutorial left me a little confused (I have pretty much no modding / modeling experience -- I'm just a digital painter). As for the animation, though, the exporter doesn't register animations even when I import one into Maya directly from the game's assets.

I'm obviously really new to this stuff but I'm happy to help you diagnose whatever my issue is -- just let me know if you need more information or I can try to send the Maya scene and corresponding files to you.

Thank you!

**Comment by ross-g** [comment]
The animation is cool, like the eye movements! :smile:

The general workflow for the tool when creating assets from scratch is that you will need to "tag" things in Maya so they are valid for export.

- Materials need a tag which specifies which shader in game they should use. Any materials which exist in the Maya scene that have the tag will be in the "Materials" list shown in the tool UI. You should create any materials you need through the tool (to make sure they get the tag added) and then assign them to meshes. The tags that you are allowed to pick from when you create a material is based on which option you select in the "Game engine" dropdown. For Stellaris portraits you probably want to pick one of these: "PdxMeshPortrait", "PdxMeshPortraitClothes", "PdxMeshPortraitHair".

- Animations ... well I have not quite finished the tagging system for them yet :disappointed: which is why the tool UI here is disabled. But to export an animation you should just need to setup the timeline correctly in Maya and make sure to select the root bone of the skeleton you want to export. Then the option to export animation should be called "Save animation" under the "File" menu.

Hope that helps, sorry again for the poor state of the wiki here. It's on the to do list.

**Comment by Anjureux** [comment]
Alright, I re-made my materials through the exporter and now it's detecting those. When I try to save the animation though I keep getting 'Maya Node does not exist (or is not unique):: u'None''. I had the root bone selected when I did it -- is it possible I need to add an attribute or something to the root bone?

**Comment by 6ish** [comment]
This thread is a few months old, so hopefully someone is still watchign and has a fix.   I to am recieving the  'Maya Node does not exist (or is not unique):: u'None'' error.   I am working on CK3 animations using 0.8 release of the tools.  

Here's some more info:

`[io_pdx_mesh] INFO:  exporting F:/sdf.anim
[io_pdx_mesh] INFO:  writing animation info -
[io_pdx_mesh] WARNING:  FAILED to export F:/sdf.anim
[io_pdx_mesh] ERROR:  Maya Node does not exist (or is not unique):: u'None'
# Traceback (most recent call last):
#   File "C:/Users/brick/Documents/maya/scripts\io_pdx_mesh\pdx_maya\maya_ui.py", line 566, in export_anim
#     export_animfile(anim_filepath, **options)
#   File "C:/Users/brick/Documents/maya/scripts\io_pdx_mesh\pdx_maya\maya_import_export.py", line 1704, in export_animfile
#     export_bones = get_skeleton_hierarchy([root_bone])
#   File "C:/Users/brick/Documents/maya/scripts\io_pdx_mesh\pdx_maya\maya_import_export.py", line 639, in get_skeleton_hierarchy
#     root_bone.add(get_root(bone.name()))
#   File "C:\Program Files\Autodesk\Maya2020\Python\lib\site-packages\pymel\core\nodetypes.py", line 1436, in name
#     name = self._updateName(long)
#   File "C:\Program Files\Autodesk\Maya2020\Python\lib\site-packages\pymel\core\nodetypes.py", line 1323, in _updateName
#     raise general.MayaNodeError
# pymel.core.general.MayaNodeError: Maya Node does not exist (or is not unique):: u'None'`

**Comment by ross-g** [comment]
I haven't been able to reproduce the problem myself at all, but if you're willing to attach your Maya scene file then I can try to determine the problem.

It's failing to find the skeleton correctly. Is this a model and skeleton you have made from scratch, or are you creating new animations for one of the CK3 assets?

**Comment by Anjureux** [comment]
@6ish
Sorry, should have updated the thread but I just recently figured out that it seems the issue is with Maya 2020 specifically. I switched to Maya 2019 and had no issues exporting animations and meshes from then on. Hope that helps!

**Comment by 6ish** [comment]
I installed 2019 and have no problems.  I tried combing through  the files to track down what was going on but i'm not familiar enough with python and maya to fix it.  a change in api somewhere...

I using the importer to import a skeleton from the CK3 gfx folders.   Without doing anything other than importing an existing animation from the game ( i tried many other ways too), I try to export the animation as it.  I see that it is failing to recognize the selected skeleton.

After searching some more, i found other threads that pointed me at 2019.  I'd send you my scene, but unless you have 2020, it wont be usefull.  and if you did have 2020, you'd probably see the same error anyway.  Thank you.

**Comment by ross-g** [comment]
I do have Maya 2020 yes, and while I will see the same error that's a good thing because then I can work out how to fix it.

What skeleton and animation did you import and try to export again?
