### ISSUE TITLE
anim Export issue.

### ISSUE THREAD

**Issue by castox** [ross-g/io_pdx_mesh#55]
I keep getting this issues when trying to export an animation.

`Animation export failed!
Operator bpy.ops.object.select_all.poll() failed, context is incorrect
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_pdx_mesh\pdx_blender\blender_ui.py", line 581, in execute
    export_animfile(self.filepath, frame_start=context.scene.frame_start, frame_end=context.scene.frame_end)
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 1637, in export_animfile
    bpy.ops.object.select_all(action="DESELECT")
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.select_all.poll() failed, context is incorrect

location: <unknown location>:-1`

**Comment by ross-g** [comment]
Are you trying to export while in either edit mode for a mesh, or edit/pose mode for an armature?
This is usually what the "context is incorrect" message refers to.
