### ISSUE TITLE
I made an error while exporting

### ISSUE THREAD

**Issue by LGGHC** [ross-g/io_pdx_mesh#62]
Tips'bpy_prop­_collection[key]:key"Base Color"not found",Using bleder

**Comment by LGGHC** [comment]
The above problem has been solved. It is a texture problem, but new problems appear, as follows
Mesh export failed!
'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_pdx_mesh\pdx_blender\blender_ui.py", line 504, in execute
    export_meshfile(
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 1390, in export_meshfile
    pdx_data.write_meshfile(meshpath, root_xml)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_pdx_mesh\pdx_data.py", line 427, in write_meshfile
    datastring += writeObject(shape_xml, current_depth)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_pdx_mesh\pdx_data.py", line 326, in writeObject
    datastring += writeString(obj_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_pdx_mesh\pdx_data.py", line 336, in writeString
    string = string.encode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)

location: <unknown location>:-1

**Comment by LGGHC** [comment]
> One of your meshes in Blender has an illegal character in it's name. Only characters in the `Latin-1` set are allowed. eg "中国人" is not valid but "français" is fine.

Thank you very much. I have exported the model as I wish. Thank you for your contribution to CK3 mod. I have spent months making CK3 mod. The emergence of your tool has made me break through the bottleneck. Thank you!
