### ISSUE TITLE
Export path problem

### ISSUE THREAD

**Issue by KarpAPR** [ross-g/io_pdx_mesh#63]
Hello!
Im trying to export models somewhere, but every time I get this error

![3434](https://user-images.githubusercontent.com/89696219/150677806-eb1662b0-3624-4770-a905-9a9ac89ccb80.png)

**Comment by KarpAPR** [comment]
`Python:` Traceback (most recent call last):
  File "C:\Users\Rogla-Dorn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_pdx_mesh-bugfixes\pdx_blender\blender_ui.py", line 546, in execute
    export_meshfile(
  File "C:\Users\Rogla-Dorn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_pdx_mesh-bugfixes\pdx_blender\blender_import_export.py", line 1396, in export_meshfile
    pdx_data.write_meshfile(meshpath, root_xml)
  File "C:\Users\Rogla-Dorn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_pdx_mesh-bugfixes\pdx_data.py", line 489, in write_meshfile
    with open(filepath, "wb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Rogla-Dorn\\Desktop\\blender\\'

location: <unknown location>:-1

bpy.ops.io_pdx_mesh.export_mesh(filepath="C:\\Users\\Rogla-Dorn\\Desktop\\blender\\")
`
Here is a code

**Comment by ross-g** [comment]
Did you forget to name your file when you try to export?
eg
![image](https://user-images.githubusercontent.com/9258768/151636148-b819e698-7d24-4cea-a84d-89e50c94675a.png)
