### ISSUE TITLE
exporting issue with python trace back error for blender

### ISSUE THREAD

**Issue by speedysters** [ross-g/io_pdx_mesh#69]
Report: Warning
A Mesh export failed!
X [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Crusader Kings III\\game\\gfx\\models\\portraits\\attachments\\male_headgears\\secular\\western\\war_nobility_01\\'
Python: Traceback (most recent call last):
File "C:\Users\adkin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_pdx_mesh\pdx_blender\blender_ui.py", line 504, in execute
export_meshfile(
File "C:\Users\adkin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 1390, in export_meshfile
pdx_data.write_meshfile(meshpath, root_xml)
File "C:\Users\adkin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_pdx_mesh\pdx_data.py", line 492, in write_meshfile
with open(filepath, "wb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Crusader Kings III\\game\\gfx\\models\\portraits\\attachments\\male_headgears\\secular\\western\\war_nobility_01\\'
location: <unknown location>:-1
C
<img width="923" alt="Screenshot 2022-05-26 160122" src="https://user-images.githubusercontent.com/106215412/170580239-107fbd54-bf68-4a35-b334-0453f5973f52.png">

**Comment by speedysters** [comment]
this happens when i try to export a mesh

**Comment by ross-g** [comment]
You did not enter a filename when you tried to export. (picking just a folder isn't enough)
