### ISSUE TITLE
Import mesh fails at creating the material

### ISSUE THREAD

**Issue by RonaldMacdonaldTrump** [ross-g/io_pdx_mesh#8]
Mesh doesn't include vertex groups with some error texts,
I'm with 0.7, in blender 2.81.

here's the error messege.

Mesh import failed!
'NoneType' object has no attribute 'inputs'
Traceback (most recent call last):
  File "C:\Users\Ronald\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_pdx_mesh-master\pdx_blender\blender_ui.py", line 387, in execute
    bonespace=self.chk_bonespace
  File "C:\Users\Ronald\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_pdx_mesh-master\pdx_blender\blender_import_export.py", line 1122, in import_meshfile
    create_material(pdx_material, mesh, os.path.split(meshpath)[0])
  File "C:\Users\Ronald\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_pdx_mesh-master\pdx_blender\blender_import_export.py", line 671, in create_material
    shader = create_shader(PDX_material, shader_name, texture_path)
  File "C:\Users\Ronald\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_pdx_mesh-master\pdx_blender\blender_import_export.py", line 624, in create_shader
    links.new(albedo_texture.outputs['Color'], shader_root.inputs['Base Color'])
AttributeError: 'NoneType' object has no attribute 'inputs'

location: <unknown location>:-1

**Comment by ross-g** [comment]
Thanks for posting. What are you trying to import here? It would be really useful if you could upload the file to help me recreate the error.

Your error message shows that it is failing to create a Blender shader when you import. So the rest of the import (vertex groups, etc) never happens.

**Comment by RonaldMacdonaldTrump** [comment]
[Hoi.zip](https://github.com/ross-g/io_pdx_mesh/files/4112349/Hoi.zip)

I'm trying to import HOI4 meshes.

**Comment by ross-g** [comment]
This should be fixed in dfe439d034f73cac23e5e7438085f7edadc023b5 
I will close this bug once I push out a new release.

**Comment by ross-g** [comment]
This is now fixed in the newest release. (https://github.com/ross-g/io_pdx_mesh/commit/2af4c48320d0a7d213915b3ea7e0d9e07f1a7abb)
